# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift
cache: cocoapods
before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod install --project-directory=Example
script:
- pod lib lint
- set -o pipefail && xcodebuild -project UIViewController-DisplayChild.xcodeproj -scheme UIViewController-DisplayChild -sdk iphonesimulator11.4 ONLY_ACTIVE_ARCH=NO | xcpretty
